### ISSUE TITLE
Q: Why decoupling?

### ISSUE THREAD

**Issue by PJaros** [jxmot/ESP8266-RCWL0516#4]
I'm planing to build a ESP8266 RCWL0516 but didn't plan to decouple it.

Did you build it that way because you got errournous results with a different build? Have you tried a simpler variation before you concluded to build it like that?

**Comment by jxmot** [comment]
Hello,

Anytime I work with a module that is unknown to me I tend to play it safe. This is from previous experiences where a module _should_ have been safe but wasn't. This was the primary reason for building it with an opto-isolator.

The decision was also driven by the cost of replacing the NodeMCU vs the RCWL01516 (_if defective_). For example, the cost of the NodeMCU is about $9 and the RCWL0516 is about $2, and the opto-isolator was less than $1. 

In addition it seems that the RCWL0516 can accept 4–28 VDC for it's power supply. There was a time where I was going to experiment with supplying it with 12VDC to see if that had any effect on range or behavior. In that situation the isolation is a necessity to keep from damaging the NodeMCU in case there's a failure of the RCWL0516.

A future version of the project may replace the NodeMCU with an ESP-01. In that version I will probably still use the opto-isolator, and supply the 3.3v to the ESP-01S from a dedicated regulator (5v to 3.3v).

**TIP :** When using pre-built circuits that can be operated _independent_ of support circuitry it's almost always a good idea to test them out before wiring them in. This was one of those situations. One of the RCWL0516 boards I bought was defective and output a constant 5v on the "OUT" pin.

**Comment by chupocro** [comment]
You can use 3V3 output pin of RCWL-0516 for powering it with 3.3 V and in that case even failure wouldn't damage the ESP8266.
