### ISSUE TITLE
Sensor too sensitive

### ISSUE THREAD

**Issue by guptamp** [jxmot/ESP8266-RCWL0516#5]
Hello jxmot,

I followed your instructions and everything is working but it seems too good...
The sensor is even triggered in an empty unoccupied room about every 30-90s.
Do you have any idea how to decrease sensitivity?

**Comment by jxmot** [comment]
Hello, first I recommend testing the sensor without connecting it to an MCU. You can power up the sensor independent of the rest of the circuit.

Take a look at the schematic in the README and replace the NTE3042 with a regular LED. Be sure that the polarity is correct and that the resistor is also present. After it's wired and powered up observe the LED. Does it exhibit the same behavior? If **yes** then the sensor is likely to be defective. if **no** then there might be an error in the code that is reading the device on your MCU.

You can also connect a volt meter in place of the LED.

There are several things to remember about the sensor : 

1. It is sensitive, a very minor amount of movement within its _field_ can trigger a response. 
2. It can detect presence from the back of the sensor, although not as sensitive as from the front.
3. It can also detect from the sides as well, although it's not as sensitive as the front and back sides.
4. The range of the sensor is very good from the front, I was able to easily detect a human at a distance of about 10 feet (3 meters).
5. At shorter distances from the sensor very minor changes within its _field_ can be detected. 

I hope that helps!
